<a href="https://colab.research.google.com/github/Nyfeu/Data-Science/blob/main/Ex_groupby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<head>
  <meta name="author" content="Rogério de Oliveira">
  <meta institution="author" content="ITM">
</head>

<img src="https://maua.br/images/selo-60-anos-maua.svg" width=300, align="right">
<!-- <h1 align=left><font size = 6, style="color:rgb(200,0,0)"> optional title </font></h1> -->

In [1]:
import pandas as pd
import numpy as np

## **CASE Tips**

# Q1.

Considere a base de dados [`tips`](https://github.com/Rogerio-mack/IMT_Ciencia_de_Dados/raw/main/data/tips.csv). Considerando somente os finais de semana, quem tem média de participantes na mesa maior, fumantes ou não fumantes? **`[NoGroup | GroupBy]`**

In [20]:
df = pd.read_csv('https://github.com/Rogerio-mack/IMT_Ciencia_de_Dados/raw/main/data/tips.csv')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [21]:
df_tips = df.copy()

# Filtrando apenas finais de semana (Sat, Sun)
weekend_df = df_tips[df_tips['day'].isin(['Sat', 'Sun'])]

# Agrupando por fumante e calculando a média de 'size'
result = weekend_df.groupby('smoker')['size'].mean()

display(result)

if result['Yes'] > result['No']:
    print(f"\nFumantes têm uma média maior: {result['Yes']:.2f}")
else:
    print(f"\nNão fumantes têm uma média maior: {result['No']:.2f}")

smoker
No     2.764706
Yes    2.508197
Name: size, dtype: float64

Não fumantes têm uma média maior: 2.76

## **CASE Insurance**

Acesse a base de dados [`insurance`](https://github.com/Rogerio-mack/IMT_Ciencia_de_Dados/raw/main/data/insurance.csv) para as questões a seguir.

In [23]:
df = pd.read_csv('https://github.com/Rogerio-mack/IMT_Ciencia_de_Dados/raw/main/data/insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

# Q2.

Qual percentual de homens e mulheres assegurados na base? **`[NoGroup | GroupBy]`**

In [13]:
# Calculando o percentual de homens e mulheres usando groupby
sex_counts = df.groupby('sex').size() / len(df) * 100

print("Percentual de assegurados por sexo (usando groupby):")
display(sex_counts.map('{:.2f}%'.format))

Percentual de assegurados por sexo (usando groupby):

sex
female    49.48%
male      50.52%
dtype: object

# Q3.

Qual o total do valor de seguro pago por homens e mulheres segurados na base? **`[NoGroup | GroupBy]`**

In [7]:
total_value = df.groupby('sex')['charges'].sum()

print("Total do valor de seguro pago por homens e mulheres segurados na base:")
display(total_value.map('${:,.2f}'.format))

Total do valor de seguro pago por homens e mulheres segurados na base:

sex
female    $8,321,061.19
male      $9,434,763.80
Name: charges, dtype: object

# Q4.

Qual o percentual de valor de seguros pagos por homens e mulheres segurados na base? **`[NoGroup | GroupBy]`**

In [9]:
# Somatória de toda a receita
sum_total = df['charges'].sum()

# Calculando o percentual com base em total value por gênero
percentual_value = df.groupby('sex')['charges'].sum() / sum_total * 100

print("Percentual de valor de seguros pagos por homens e mulheres segurados na base:")
display(percentual_value.map('{:.2f}%'.format))

Percentual de valor de seguros pagos por homens e mulheres segurados na base:

sex
female    46.86%
male      53.14%
Name: charges, dtype: object

# Q5.

Não fumantes apresentam em média mais filhos? **`[NoGroup | GroupBy]`**

In [11]:
children_mean = df.groupby('smoker')['children'].mean()

display(children_mean)

smoker
no     1.090226
yes    1.113139
Name: children, dtype: float64

# Q6.

Qual a média e maior de idade dentre os segurados homem, das regiões northwest ou northeast? **`[NoGroup | GroupBy]`**

In [18]:
# Calculando a média e a maior idade agrupado por sexo e região
result = df.groupby(['sex', 'region'])['age'].agg(['mean', 'max'])
filtered_df = result.loc[('male', ['northwest', 'northeast']), :]

print("Média e maior idade de homens nas regiões northwest e northeast:")
display(filtered_df)

Média e maior idade de homens nas regiões northwest e northeast:

                     mean  max
sex  region
male northwest  38.795031   64
     northeast  38.901840   64